#!/bin/bash

cboxclustername="$1"

for i in $(virsh list --all | grep $cboxclustername | awk '{print $2}'); do
	virsh destroy $i
	virsh undefine $i
done

rm -f /root/.ssh/known_hosts

virsh net-destroy $cboxclustername-br0
virsh net-undefine $cboxclustername-br0

mv -f /etc/hosts.cbox /etc/hosts
service fence_virtd stop
mv -f /etc/fence_virt.conf.cbox /etc/fence_virt.conf

rm -rf /usr/share/cbox

rm -rf /srv/cbox
