#!/bin/bash

virsh net-destroy cluster
virsh net-undefine cluster
mv -f /etc/hosts.cbox /etc/hosts
service fence_virtd stop
mv -f /etc/fence_virtd.conf.cbox /etc/fence_virtd.conf

rm -f /usr/share/cbox

rm -rf /srv/cbox
