.TH CBOX "8" "February 2011" "cbox" "System/Cluster Administration Utilities"
.SH NAME
cbox \- manual page for cbox usage
.SH DESCRIPTION
Usage:
.PP
cbox [options]
.SH OPTIONS
.TP
\fB\-c\fR cluster_name
set clustername (default: testcluster)
.TP
\fB\-d\fR
development mode. Will repeat failed hook.
.TP
\fB\-f\fR
force switch to skip all questions. Use with care!
.TP
\fB\-k\fR kickstart
use custom kickstart file. This overrides both \-O and \-r.
.TP
\fB\-m\fR [pacemaker|rgmanager|none]
use a resource manager (default: none)
.TP
\fB\-n\fR number_of_nodes
a value between 2 and 16 (default: 2)
.TP
\fB\-o\fR path_to_storage_dir
set path where to store VMs (default: /srv/cbox)
.TP
\fB\-O\fR osname
use kickstart without fedora prefix distributed with cbox. This overrides \-r.
.TP
\fB\-q\fR
enable qdiskd for cman clusters (default: no)
.TP
\fB\-r\fR fedora_release
force fedora release to install on the nodes (defaults: autodetect/same as host)
.TP
\fB\-t\fR [cman|corosync]
define cluster type (default: cman)
.TP
\fB\-u\fR repo_URL
define additional yum repository for kickstart (default: none)
.TP
\fB\-C\fR
enable appliance-creator cache (stored in /srv/cbox/accache)
.TP
\fB\-E\fR regexp
exclude given script (regexp is matched by =~ bash operator). Let's say you want
to exclude all gfs2, guest_setup (clvmd, ...) and enable of deamons, just use
\-E "(gfs2|guest_setup|guest_enable)"
.TP
\fB\-D\fR
enable creation of driver node. Driver node is base node without additional
configuration (hacks with number 62_ and larger are not applied), so it's also out
of fencing. It's not included in cluster configuration. Feature is useful as driver
node for tests (like CTS) or for standalone management node. Driver node is fully
preconfigured for password-less ssh to other cluster nodes.
.TP
\fB\-h\fR
this help
.TP
\fB\-v\fR virt_opts
define virtual nodes and storage size in a comma separated list of parameters
.IP
valid parameters are:

ram=XXX                     amount of RAM (for each node) in MB (min. 512 \- default 2048)

cpus=XXX                    number of virtual cpus

root=XXX                    size of the root partition in MB (min. 2048 \- default 4096)

swap=XXX                    size of the swap partition in MB (min. 512 \- default is 1024)

share=XXX                   size of the shared storage disk in MB (min. 20544 \- default 20544)
