#!/bin/bash

set -e

echo "Installing required packages on host system"

yum install -y \
	libvirt libvirt-client qemu-system-x86 \
	virt-install libguestfs-mount libguestfs-tools libguestfs-tools-c \
	fence-virtd fence-virtd-multicast fence-virtd-libvirt \
	openssh-clients ntp

exit 0
