#!/bin/bash

set -e

echo "Installing required packages on host system"

yum install -y \
	libvirt libvirt-client qemu-system-x86 \
	appliance-tools libguestfs-mount \
	fence-virtd fence-virtd-multicast fence-virtd-libvirt \
	openssh-clients

exit 0
