#!/bin/bash

set -e

echo "Starting libvirtd service"

service libvirtd start

echo "Checking if cluster virt net already exists"
virsh net-list |grep -q ^$cboxclustername-br0 && {
	echo "$cboxclustername-br0 virt net detected: aborting"
	exit 1
}

echo "Making a backup copy of main host /etc/hosts to /etc/hosts.cbox"
cp /etc/hosts /etc/hosts.cbox

echo "Generating libvirt $cboxclustername-br0 xml template"
tempfile="$cboxtempdir/libvirt-net.xml"

cat > "$tempfile" << EOF
<network>
  <name>$cboxclustername-br0</name>
  <uuid>$(uuidgen)</uuid>
  <forward mode='nat'/>
  <bridge name='$cboxclustername-br0' stp='off' delay='0'/>
  <ip address='192.168.123.254' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.123.1' end='192.168.123.253'/>
EOF

for i in $(seq 1 $cboxnumnodes); do
	echo "      <host mac='54:52:00:00:00:$(printf '%x' $i)' name='$cboxclustername-node$i' ip='192.168.123.$i' />" >> "$tempfile"
	echo "Adding 192.168.123.$i $cboxclustername-node$i to main host /etc/hosts"
	echo "192.168.123.$i $cboxclustername-node$i" >> /etc/hosts
done

cat >> "$tempfile" << EOF
    </dhcp>
  </ip>
</network>
EOF

echo "XML result:"
cat "$tempfile"

echo "Updating main host /etc/hosts"
echo "192.168.123.254 $cboxclustername-host" >> /etc/hosts

echo "Adding $cboxclustername-br0 to libvirt"
virsh net-define "$tempfile"
echo "Setting $cboxclustername-br0 to start automatically"
virsh net-autostart $cboxclustername-br0
echo "Starting $cboxclustername-br0"
virsh net-start $cboxclustername-br0

rm -f "$tempfile"

exit 0
