#!/bin/bash

set -e

echo "Configuring fence_virtd on main host"

echo "Making a backup copy of main host /etc/fence_virt.conf to /etc/fence_virt.conf.cbox"
mv -f /etc/fence_virt.conf /etc/fence_virt.conf.cbox

echo "Generating new config"
cat > /etc/fence_virt.conf << EOF
backends {
	libvirt {
		uri = "qemu:///system";
	}
}

listeners {
	multicast {
		interface = "$cboxclustername-bridge0";
		port = "1229";
		family = "ipv4";
		address = "225.0.0.12";
	}
}

fence_virtd {
	module_path = "/usr/lib64/fence-virt";
	backend = "libvirt";
	listener = "multicast";
}
EOF

echo "Enabling fence_virtd to run on main host"
chkconfig fence_virtd on
echo "Starting fence_virtd"
service fence_virtd restart

exit 0
