#!/bin/bash

set -e

mv -f /etc/fence_virt.conf /etc/fence_virt.conf.cbox

cat > /etc/fence_virt.conf << EOF
backends {
	libvirt {
		uri = "qemu:///system";
	}
}

listeners {
	multicast {
		interface = "cluster-bridge0";
		port = "1229";
		family = "ipv4";
		address = "225.0.0.12";
	}
}

fence_virtd {
	module_path = "/usr/lib64/fence-virt";
	backend = "libvirt";
	listener = "multicast";
}
EOF

[ -n "$(which restorecon)" ] && {
	restorecon /etc/fence_virt.conf
}
chkconfig fence_virtd on
service fence_virtd start

exit 0
