#!/bin/bash

set -e

cd /root
mkdir -p .ssh
rm -f .ssh/id_rsa_$cboxclustername*
ssh-keygen -q -N '' -C '' -t rsa -b 2048 -f .ssh/id_rsa_$cboxclustername >&/dev/null
chmod 0600 .ssh/id_rsa_$cboxclustername.pub

exit 0
