#!/bin/bash

set -e

echo "Generating cbox-guest.ks"

cd $cboxtempdir

# need to think if there is a better way to do this without
# reinventing debian-installer receipts for disk paritioning

# priciple of ops:
# disk size - 64MB for qdisk
# free space / 2 (one for gfs2 and one for clvmd)

freespace=$cboxvirtshare
qdiskdsize=64
freespace=$((freespace - qdiskdsize))
gfs2size=$((freespace / 2))
freespace=$((freespace - gfs2size))
clvmdsize=$freespace

[ -f /etc/sysconfig/clock ] && . /etc/sysconfig/clock
[ -z "$ZONE" ] && ZONE="America/New_York"

[ -n "$cboxrepourl" ] && repourl="repo --name=\"localrepo\" --baseurl=$cboxrepourl"

cat "$cboxkickstart" | sed \
	-e 's#@TIMEZONE@#'$ZONE'#g' \
	-e 's#@ROOTSIZE@#'$cboxvirtroot'#g' \
	-e 's#@SWAPSIZE@#'$cboxvirtswap'#g' \
	-e 's#@QDISKDSIZE@#'$qdiskdsize'#g' \
	-e 's#@GFS2SIZE@#'$gfs2size'#g' \
	-e 's#@CLVMDSIZE@#'$clvmdsize'#g' \
	-e "s#@REPOURL@#$repourl#g" \
	> cbox-guest.ks

# Add specific cluster packages
sed -i "/\# CLUSTER_PACKAGES/r $cboxdatadir/packages_$cboxclustertype.ks" cbox-guest.ks

exit 0
