#!/bin/bash

set -e

echo "Creating main/first VM in $cboxtempdir (this will take time!)"

cd $cboxtempdir

appliance-creator -v --vmem=2048 --vcpu=2 \
		  -n $cboxclustername-boot \
		  -c $cboxdatadir/fedora-$cboxfedrelease.ks

rm -f $cboxclustername-boot/$cboxclustername-boot.xml

exit 0
