#!/bin/bash

set -e

echo "Creating main/first VM in $cboxtempdir (this will take time!)"

cd $cboxtempdir
mkdir -p $cboxclustername-boot

eval $(grep IMAGE_TREE cbox-guest.ks | sed -e 's/#//')

# Hack +100M for bios partition
ROOT_DISK_GB=$((($cboxvirtroot + $cboxvirtswap + 100 + 1023) / 1024))
SHARED_DISK_GB=$((($cboxvirtshare + 1023) / 1024))

truncate -s ${ROOT_DISK_GB}G $cboxclustername-boot/$cboxclustername-boot-vda.raw
truncate -s ${SHARED_DISK_GB}G $cboxclustername-boot/$cboxclustername-boot-vdb.raw

virt-install --connect=qemu:///system \
    --network=bridge:testcluster-br0,mac=54:52:00:00:00:1 \
    --network=bridge:testcluster-br1,mac=54:52:00:00:01:1 \
    --initrd-inject=cbox-guest.ks \
    --extra-args="ks=file:/cbox-guest.ks serial console=ttyS0,115200" \
    --name=$cboxclustername-boot \
    --disk path=$cboxclustername-boot/$cboxclustername-boot-vda.raw,format=raw,sparse=true,size=$ROOT_DISK_GB \
    --disk path=$cboxclustername-boot/$cboxclustername-boot-vdb.raw,format=raw,sparse=true,size=$SHARED_DISK_GB \
    --ram $cboxvirtram \
    --vcpus=$cboxvirtcpus \
    --check-cpu \
    --accelerate \
    --hvm \
    --location=$IMAGE_TREE \
    --nographics \
    --noreboot

rm -f $cboxclustername-boot/$cboxclustername-boot.xml

exit 0
