#!/bin/bash

set -e

echo "Creating main/first VM in $cboxtempdir (this will take time!)"

cd $cboxtempdir

appliance-creator -v --vmem=$cboxvirtram --vcpu=$cboxvirtcpus \
		  -n $cboxclustername-boot \
		  -c cbox-guest.ks -d

rm -f $cboxclustername-boot/$cboxclustername-boot.xml

exit 0
