#!/bin/bash

set -e

echo "Mounting main/first VM disk in $cboxtempdir/$cboxclustername-mount"

cd $cboxtempdir

mkdir -p $cboxclustername-mount

IMG=$cboxclustername-boot/$cboxclustername-boot-vda.raw

PART=1
# GPT uses additional biosboot partition (no fs there)
blkid -p $IMG | grep gpt && PART=2

if [ -z "$cboxuseloop" ]; then
	# Get libguestfs device name
	dev_name=`virt-filesystems --block-devices -a $IMG`
	guestmount  -a $IMG -m $dev_name$PART $cboxclustername-mount
else
	name=$(kpartx -p p -a $IMG -v | grep p$PART | cut -d' ' -f 3)
	mount /dev/mapper/$name $cboxclustername-mount
fi

exit 0
