#!/bin/bash

set -e

echo "Mounting main/first VM disk in $cboxtempdir/$cboxclustername-mount"

cd $cboxtempdir

mkdir -p $cboxclustername-mount

guestmount \
	-a $cboxclustername-boot/$cboxclustername-boot-vda.raw \
	-m /dev/vda1 \
	$cboxclustername-mount

exit 0
