#!/bin/bash

set -e

echo "Configure guest network"

cd $cboxtempdir

echo "Make a backup copy of guest /etc/hosts to /etc/hosts.cbox"

cp $cboxclustername-mount/etc/hosts \
   $cboxclustername-mount/etc/hosts.cbox

echo "Update guest /etc/hosts"

cat /etc/hosts | \
	grep $cboxclustername \
	>> $cboxclustername-mount/etc/hosts

echo "Make a backup copy of guest /etc/sysconfig/network to /etc/sysconfig/network.cbox"

cp $cboxclustername-mount/etc/sysconfig/network \
   $cboxclustername-mount/etc/sysconfig/network.cbox

echo "Strip HOSTNAME to allow dhcp to set the correct one for us"

sed -i -e 's#HOSTNAME.*##g' \
   $cboxclustername-mount/etc/sysconfig/network

echo "Strip HWADDR from network config to allow new setting later"

sed -i -e 's#HWADDR.*##g' \
   $cboxclustername-mount/etc/sysconfig/network-scripts/ifcfg-eth0
sed -i -e 's#HWADDR.*##g' \
   $cboxclustername-mount/etc/sysconfig/network-scripts/ifcfg-eth1

exit 0
