#!/bin/bash

set -e

cd /srv/cbox/$cboxclustername

echo "Fix guests /etc/fstab"

cp $cboxclustername-mount/etc/fstab \
   $cboxclustername-mount/etc/fstab.cbox

sed -i \
   -e 's%.*vdb.*clvm.*%## &%g' \
   -e 's%.*vdb.*qdisk.*%## &%g' \
   -e 's%gfs2.*ext3%gfs2 gfs2%g' \
   $cboxclustername-mount/etc/fstab

cat $cboxclustername-mount/etc/fstab | grep gfs2 | awk '{print $1}' > gfs2_partition
cat $cboxclustername-mount/etc/fstab | grep qdiskd | awk '{print $2}' > qdiskd_partition
cat $cboxclustername-mount/etc/fstab | grep clvmd | awk '{print $2}' > clvmd_partition

echo "/dev/$cboxclustername-vg/$cboxclustername-lv /srv/cbox/clvmd gfs2 defaults,noatime 0 0" >> \
	$cboxclustername-mount/etc/fstab

exit 0
