#!/bin/bash

set -e

echo "Install $cboxclustername ssh pub key in the guest"

cd $cboxtempdir

mkdir -p $cboxclustername-mount/root/.ssh
cp /root/.ssh/id_rsa_$cboxclustername.pub \
   $cboxclustername-mount/root/.ssh/authorized_keys

chmod 0400 $cboxclustername-mount/root/.ssh/authorized_keys

exit 0
