#!/bin/bash

set -e

[ "$cboxclustertype" != "cman" ] && exit 0

cd $cboxtempdir

echo "Creating RHCS /etc/cluster/cluster.conf in the guest"

if [ -z "$cboxqdiskd" ]; then
	if [ "$cboxnumnodes" = "2" ]; then
		cmanvotes='two_node="1" expected_votes="1"'
	else
		cmanvotes='expected_votes="'$cboxnumnodes'"'
	fi
else
	expected_votes=$((cboxnumnodes + 1))
	cmanvotes='expected_votes="'$expected_votes'"'
	forcevotes='votes="1"'
fi

cat > $cboxclustername-mount/etc/cluster/cluster.conf << EOF
<?xml version="1.0"?>

<cluster name="$cboxclustername" config_version="1" >
  <logging debug="on"/>
  <cman $cmanvotes/>
  <clusternodes>
EOF

for i in $(seq 1 $cboxnumnodes); do

cat >> $cboxclustername-mount/etc/cluster/cluster.conf << EOF
    <clusternode name="$cboxclustername-node$i-br1" nodeid="$i" $forcevotes>
      <fence>
        <method name="single">
          <device name="xvm" domain="$cboxclustername-node$i"/>
        </method>
      </fence>
    </clusternode>
EOF

done

cat >> $cboxclustername-mount/etc/cluster/cluster.conf << EOF
  </clusternodes>
EOF

if [ -z "$cboxqdiskd" ]; then
cat >> $cboxclustername-mount/etc/cluster/cluster.conf << EOF
  <!--
EOF
fi

cat >> $cboxclustername-mount/etc/cluster/cluster.conf << EOF
  <quorumd label="$cboxclustername-qdiskd">
   <heuristic program="ping $cboxclustername-host -c1 -t1" score="1" interval="2" tko="3"/>
  </quorumd>
EOF

if [ -z "$cboxqdiskd" ]; then
cat >> $cboxclustername-mount/etc/cluster/cluster.conf << EOF
  -->
EOF
fi

cat >> $cboxclustername-mount/etc/cluster/cluster.conf << EOF
  <fencedevices>
    <fencedevice name="xvm" agent="fence_xvm" interface="eth1"/>
  </fencedevices>
</cluster>
EOF

exit 0
