#!/bin/bash

set -e

echo "Apply distribution/version specific hacks pre-run"

cd $cboxtempdir

chroot $cboxclustername-mount su - root -c "chkconfig iptables off"
chroot $cboxclustername-mount su - root -c "chkconfig ip6tables off"

exit 0
