#!/bin/bash

set -e

echo "Apply distribution/version specific hacks pre-run"

cd $cboxtempdir

chroot $cboxclustername-mount su -c "chkconfig iptables off" && true
chroot $cboxclustername-mount su -c "chkconfig ip6tables off" && true

exit 0
