#!/bin/bash

set -e

cd /srv/cbox/$cboxclustername

echo "applying version specific hacks"

if [ "$cboxfedrelease" = "13" ]; then
	echo "Removing Fedora 13 udev persistent net rules generator"
	rm -f $cboxclustername-mount/lib/udev/rules/*persistent-net*
fi

exit 0
