#!/bin/bash

set -e

echo "Apply distribution/version specific hacks (the pain!)"

cd $cboxtempdir

if [ "$cboxfedrelease" = "13" ]; then
	echo "Removing Fedora 13 udev persistent net rules generator"
	rm -f $cboxclustername-mount/lib/udev/rules.d/*persistent-net*
fi

exit 0
