#!/bin/bash

set -e

echo "Un-mount main/first VM disk"

cd $cboxtempdir

umount $cboxclustername-mount

if [ -n "$cboxuseloop" ]; then
    kpartx -d $cboxclustername-boot/$cboxclustername-boot-vda.raw
fi

echo "Syncing data (might take sometime)"

sync

rm -rf $cboxclustername-mount

exit 0
