#!/bin/bash

set -e

echo "Creating first node"

cd $cboxvmsdir/$cboxclustername

echo "Moving disks"

mv $cboxtempdir/$cboxclustername-boot/$cboxclustername-boot-vda.raw \
   $cboxclustername-node1.raw

mv $cboxtempdir/$cboxclustername-boot/$cboxclustername-boot-vdb.raw \
   $cboxclustername-shareddisk.raw

echo "Generating $cboxclustername-node1 libvirt xml template"

memory=$((cboxvirtram * 1024))

cat $cboxdatadir/libvirt_template.xml | sed \
	-e 's#@NAME@#'$cboxclustername-node1'#g' \
	-e 's#@UUID@#'$(uuidgen)'#g' \
	-e 's#@MEMORY@#'$memory'#g' \
	-e 's#@VCPUS@#'$cboxvirtcpus'#g' \
	-e 's#@DISK@#'$cboxvmsdir/$cboxclustername/$cboxclustername-node1.raw'#g' \
	-e 's#@SHAREDDISK@#'$cboxvmsdir/$cboxclustername/$cboxclustername-shareddisk.raw'#g' \
	-e 's#@MACADDRESS@#54:52:00:00:00:1#g' \
	-e 's#@BRIDGE@#'$cboxclustername-br0'#g' \
	> $cboxclustername-node1.xml

echo "Defining $cboxclustername-node1 in libvirt"

virsh define $cboxclustername-node1.xml

exit 0
