#!/bin/bash

set -e

echo "Starting $cboxclustername-node1"

virsh start $cboxclustername-node1

max=60
count=0
while ! ssh $cboxclustername-node1 \
	-i /root/.ssh/id_rsa_$cboxclustername \
	-o StrictHostKeyChecking=no -o ConnectTimeout=2 "sleep 1"; do
	echo "Wating for $cboxclustername-node1 to boot"
	sleep 5
	[ "$max" -eq "$count" ] && {
		echo "ERROR: $cboxclustername-node1 did not respond to ssh after 300 seconds"
		exit 1
	}
	count=$((count+1))
done

ssh $cboxclustername-node1-br1 \
    -i /root/.ssh/id_rsa_$cboxclustername \
    -o StrictHostKeyChecking=no "sleep 1"

# Add local repository
if [ -n "$cboxrepourl" ] ; then
    REPO="[localrepo]\nname=localrepo\nbaseurl=$cboxrepourl\nenabled=1\ngpgcheck=0\n"
    ssh $cboxclustername-node1 \
	-i /root/.ssh/id_rsa_$cboxclustername \
	-o StrictHostKeyChecking=no \
	"[ -d /etc/yum.repos.d ] && echo -e '$REPO' >/etc/yum.repos.d/local.repo"
fi

exit $?
