#!/bin/bash

set -e

echo "Starting main guest"

virsh start $cboxclustername-node1

max=60
count=0
while ! ssh $cboxclustername-node1 \
	-i /root/.ssh/id_rsa_$cboxclustername \
	-o StrictHostKeyChecking=no "sleep 5"; do
	echo "Wating for $cboxclustername-node1 to boot"
	sleep 5
	[ "$max" -eq "$count" ] && {
		echo "ERROR: $cboxclustername-node1 did not respond to ssh after 300 seconds"
		exit 1
	}
	count=$((count+1))
done

exit 0
