#!/bin/bash

set -e

[ "$cboxclustertype" != "corosync" -a "$cboxclustertype" != "cman" ] && exit 0

cd $cboxtempdir

echo "Creating gfs2 filesystem on $(cat gfs2_partition)"

ssh $cboxclustername-node1 \
	-i /root/.ssh/id_rsa_$cboxclustername \
	-o StrictHostKeyChecking=no \
	"mkfs.gfs2 -j 16 -O -t $cboxclustername:gfs2 $(cat "gfs2_partition")"

exit 0
