#!/bin/bash

set -e

echo "Enable cluster daemons"

cd /srv/cbox/$cboxclustername

for i in clvmd cman cmirrord gfs2 gfs2-cluster modclusterd rgmanager ricci; do
	ssh $cboxclustername-node1 \
		-i /root/.ssh/id_rsa_$cboxclustername \
		-o StrictHostKeyChecking=no \
		"chkconfig $i on"
done

exit 0
