#!/bin/bash

set -e

echo "Enabling cluster daemons in the guest"

enable_daemon() {
	daemon="$1"
	ssh $cboxclustername-node1 \
		-i /root/.ssh/id_rsa_$cboxclustername \
	-o StrictHostKeyChecking=no \
		"chkconfig $daemon on"
	echo "$daemon enabled"
}

daemons=""

[ "$cboxclustertype" = "cman" ] && \
	daemons="$daemons clvmd cman cmirrord gfs2 modclusterd ricci"
        try_daemons="gfs2-cluster"

[ "$cboxclustertype" = "corosync" ] && \
	daemons="$daemons corosync dlm clvmd cmirrord"

[ "$cboxrasmngr" != "none" ] && daemons="$daemons $cboxrasmngr"

for i in $daemons ntpd ntpdate; do
	enable_daemon $i
done

for i in $try_daemons; do
	enable_daemon $i || echo "WARNING: Daemon $i failed."
done

exit 0
