#!/bin/bash

set -e

echo "Apply distribution/version specific hacks live"

cd $cboxtempdir

echo "Removing udev persistent net generated rules"
ssh $cboxclustername-node1 \
	-i /root/.ssh/id_rsa_$cboxclustername \
	-o StrictHostKeyChecking=no \
	"rm -f /etc/udev/rules.d/*persistent-net*"

exit 0
