#!/bin/bash

set -e

echo "Stopping main guest"

virsh shutdown $cboxclustername-node1

max=60
count=0
while [ -n "$(virsh list | grep $cboxclustername-node1 | awk '{print $2}')" ]; do
	sleep 5
	[ "$max" -eq "$count" ] && {
		echo "ERROR: $cboxclustername-node1 did not shutdown after 300 seconds"
		exit 1
	}
	count=$((count+1))
done

exit 0
