#!/bin/bash

set -e

echo "Cloning $cboxclustername-node1 (this will take time)"

cd $cboxvmsdir/$cboxclustername

for i in $(seq 2 $cboxnumnodes); do
	echo "Creating $cboxclustername-node$i boot disk"
	cp $cboxclustername-node1.raw $cboxclustername-node$i.raw


	echo "Creating $cboxclustername-node$i libvirt xml template"
	cat $cboxdatadir/libvirt_template.xml | sed \
		-e 's#@NAME@#'$cboxclustername-node$i'#g' \
		-e 's#@UUID@#'$(uuidgen)'#g' \
		-e 's#@MEMORY@#2097152#g' \
		-e 's#@VCPUS@#2#g' \
		-e 's#@DISK@#'$cboxvmsdir/$cboxclustername/$cboxclustername-node$i.raw'#g' \
		-e 's#@SHAREDDISK@#'$cboxvmsdir/$cboxclustername/$cboxclustername-shareddisk.raw'#g' \
		-e 's#@MACADDRESS@#54:52:00:00:00:'$(printf '%x' $i)'#g' \
		-e 's#@BRIDGE@#'$cboxclustername-br0'#g' \
		> $cboxclustername-node$i.xml

	echo "Defining $cboxclustername-node$i in libvirt"
	virsh define $cboxclustername-node$i.xml
done

exit 0
