#!/bin/bash

set -e

echo "Cloning $cboxclustername-node1 (this will take time)"

cd $cboxvmsdir/$cboxclustername

memory=$((cboxvirtram * 1024))

for i in $(seq 2 $cboxnumnodes); do
	echo "Creating $cboxclustername-node$i boot disk"
	cp --sparse=always $cboxclustername-node1.raw $cboxclustername-node$i.raw

	if [ "$cboxclustertype" = "ceph" ] ; then
	    SHAREDIMG=$cboxclustername-node$i-shareddisk.raw
	    cp --sparse=always $cboxclustername-node1-shareddisk.raw $SHAREDIMG
	else
	    SHAREDIMG=$cboxclustername-shareddisk.raw
	fi

	echo "Creating $cboxclustername-node$i libvirt xml template"
	cat $cboxdatadir/libvirt_template.xml | sed \
		-e 's#@NAME@#'$cboxclustername-node$i'#g' \
		-e 's#@UUID@#'$(uuidgen)'#g' \
		-e 's#@MEMORY@#'$memory'#g' \
		-e 's#@VCPUS@#'$cboxvirtcpus'#g' \
		-e 's#@DISK@#'$cboxvmsdir/$cboxclustername/$cboxclustername-node$i.raw'#g' \
		-e 's#@SHAREDDISK@#'$cboxvmsdir/$cboxclustername/$SHAREDIMG'#g' \
		-e 's#@MACADDRESS0@#54:52:00:00:00:'$(printf '%x' $i)'#g' \
		-e 's#@BRIDGE0@#'$cboxclustername-br0'#g' \
		-e 's#@MACADDRESS1@#54:52:00:00:01:'$(printf '%x' $i)'#g' \
		-e 's#@BRIDGE1@#'$cboxclustername-br1'#g' \
		-e 's#@EMULATOR@#'$cboxemulator'#g' \
		> $cboxclustername-node$i.xml

	echo "Defining $cboxclustername-node$i in libvirt"
	virsh define $cboxclustername-node$i.xml
done

exit 0
