#!/bin/bash

set -e

echo "Setting cluster nodes to autostart"

nodes=$(seq 1 $cboxnumnodes)

[ "$cboxdrivernode" == "yes" ] && nodes="$nodes -driver"

for i in $nodes; do
	virsh autostart $cboxclustername-node$i
done

exit 0
