#!/bin/bash

set -e

echo "Booting all cluster nodes"

nodes=$(seq 1 $cboxnumnodes)
[ "$cboxdrivernode" == "yes" ] && nodes="$nodes -driver"

for i in $nodes; do
	virsh start $cboxclustername-node$i
done

echo "Wait for nodes to boot and update main host .ssh/known_hosts"

function ping_host() {
	max=60
	count=0

	# Avoid "no route to host" errors while hosts are starting
	while ! ping -q -c 1 $1 >/dev/null ; do
		count=$((count+1))
		[ "$max" -eq "$count" ] && {
			echo "WARNING: $1 did not respond to ping after $max seconds"
			exit 1
		}
		sleep 1
	done
}

# not ideal but let's not make it too complicated
for i in $nodes; do
	max=60
	count=0

	ping_host $cboxclustername-node$i
	while ! ssh $cboxclustername-node$i \
		-i /root/.ssh/id_rsa_$cboxclustername \
		-o StrictHostKeyChecking=no -o ConnectTimeout=2 "sleep 1"; do
		echo "Wating for $cboxclustername-node$i to boot"
		sleep 5
		[ "$max" -eq "$count" ] && {
			echo "WARNING: $cboxclustername-node$i did not respond to ssh after 300 seconds"
			exit 1
		}
		count=$((count+1))
	done

	ping_host $cboxclustername-node$i-br1
	ssh $cboxclustername-node$i-br1 \
	    -i /root/.ssh/id_rsa_$cboxclustername \
	    -o StrictHostKeyChecking=no "sleep 1"

done

exit 0
